### ISSUE TITLE
Crash on PR 1308 Metrics Chooser

### ISSUE THREAD

**Issue by brifordwylie** [SuperCowPowers/workbench#429]
PR #426 has a crash when opening the Endpoint Page #426

```
127.0.0.1 - - [11/Mar/2024 11:23:53] "POST /_dash-update-component HTTP/1.1" 200 -
[2024-03-11 11:23:53,343] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/dash/dash.py", line 1310, in dispatch
    ctx.run(
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/dash/_callback.py", line 442, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/Users/briford/work/sageworks/applications/aws_dashboard/pages/endpoints/callbacks.py", line 82, in generate_endpoint_details_figures
    endpoint_details_markdown = model_details_markdown.ModelDetailsMarkdown().generate_markdown(endpoint_details)
  File "/Users/briford/work/sageworks/src/sageworks/web_components/model_details_markdown.py", line 34, in generate_markdown
    model_details = model.details()
AttributeError: 'dict' object has no attribute 'details'
```

**Comment by brifordwylie** [comment]
Okay, so I fixed the crash. But the endpoints page no longer has a model metrics section, which... maybe is fine... maybe having TWO places with model metrics is a bit weird.
