### ISSUE TITLE
Glue Job Error

### ISSUE THREAD

**Issue by brifordwylie** [SuperCowPowers/workbench#432]
```
2024-03-14 17:42:06,481 ERROR [main] glue.ProcessLauncher (Logging.scala:logError(77)): Error from Python:Traceback (most recent call last):
  File "/tmp/featureset_to_model.py", line 75, in <module>
    sw_model = full_fs.to_model(
  File "/home/spark/.local/lib/python3.10/site-packages/sageworks/api/feature_set.py", line 99, in to_model
    features_to_model.transform(
  File "/home/spark/.local/lib/python3.10/site-packages/sageworks/core/transforms/transform.py", line 124, in transform
    self.transform_impl(**kwargs)
  File "/home/spark/.local/lib/python3.10/site-packages/sageworks/core/transforms/features_to_model/features_to_model.py", line 100, in transform_impl
    delete_model = ModelCore(self.output_uuid, force_refresh=True)
  File "/home/spark/.local/lib/python3.10/site-packages/sageworks/core/artifacts/model_core.py", line 62, in __init__
    self.model_meta = aws_meta.get(self.model_name)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by brifordwylie** [comment]
Okay, part of the context here, is this is a Glue Job where the redis-host hasn't been set to it's hitting the in-memory cache instead of redis.
